repos:
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.0.7
    hooks:
      - id: sqlfluff-lint
        language_version: python3.9
        additional_dependencies:
          ["dbt-bigquery==1.7.2", "sqlfluff-templater-dbt==3.0.7"]

  - repo: https://github.com/dbt-checkpoint/dbt-checkpoint
    rev: v2.0.1
    hooks:
      - id: dbt-docs-generate
        files: ^(models|macros)/.*(.sql|.yml|.yaml)$
      - id: check-model-columns-have-desc
        files: ^models/marts
      - id: check-model-has-all-columns
        files: ^models/marts
      - id: check-model-has-description
        files: ^models/marts
      - id: check-model-has-properties-file
        files: ^models/(staging|intermediate)
      - id: check-source-table-has-description
        files: ^models/staging
      - id: check-macro-has-description
        files: ^macros
