models:
  - name: products
    description: >
      Product dimension table. The grain of the table is one row per product.
    columns:
      - name: product_id
        data_type: string
        description: Product ID
        tests:
          - unique
          - not_null

      - name: product_name
        data_type: string
        description: Product name

      - name: product_type
        data_type: string
        description: Product type

      - name: product_description
        data_type: string
        description: Description of the product

      - name: product_price
        data_type: numeric
        description: Price of the product

      - name: is_food_item
        data_type: boolean
        description: Flag indicating if the product is a food item

      - name: is_drink_item
        data_type: boolean
        description: Flag indicating if the product is a drink item